# Generated by Django 4.2.7 on 2024-04-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsApp', '0003_detection_image_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
